version: '3'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    command: uvicorn app.py:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8080"

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
